name: Keystone CMS Docker Build Cache Save Artifact

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clone portal cms # checkout main
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: USSF-ORBIT/ussf-portal-cms
          ref: main
          path: ./ussf-portal-cms
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
        id: buildx
        with:
          install: true

      - name: Build Keystone to e2e Stage
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
        with:
          context: ./ussf-portal-cms
          tags: keystone-cms:e2e
          cache-to: type=local,mode=max,dest=/tmp/keystone-cms,tag=e2e
          target: e2e

      - name: Get docker image digest from manifest
        id: manifest
        run: |
          digest=$(cat /tmp/keystone-cms/index.json | jq -r '.manifests[0].digest')
          echo "docker_tag=${digest##sha256:}" >> $GITHUB_OUTPUT

      - name: Save docker cache to GHA cache using image digest as key
        uses: actions/cache/save@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: /tmp/keystone-cms
          key: ${{ runner.os }}-docker-keystone-cms-${{ steps.manifest.outputs.docker_tag }}
